platform :ios, '15.0'

target 'StoryMaker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StoryMaker

  target 'StoryMakerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
